### ISSUE TITLE
O que devo aprender?

### ISSUE THREAD

**Issue by bitterteriyaki** [unb-mds/2023-2-Squad06#1]
# O que devo aprender para contribuir com este projeto?

## Sumário

Esta issue possui uma lista não exaustiva (isto é, não está completa) de ferramentas que você deve aprender para trabalhar de forma mais efetiva neste projeto. Eu sei, são muitas coisas. Você não precisa aprender tudo de uma vez. Tente aprender um pouco sobre algum assunto de forma contínua, mesmo que não aprenda tudo! Caso você tenha dificuldades sobre algum determinado assunto, não sinta vergonha em pedir ajuda e conselhos para mim ou qualquer outro colega do grupo. Lembre-se: **a força de uma corrente é dada pelo seu elo mais fraco**. Tente sempre aprimorar lugares onde você acha que está errando mais.

Esta issue presume que você já tenha lido e configurado seu ambiente de acordo com a issue #2.

#### Comandos

| Comando | Descrição | Prioridade |
| --- | --- | :-: |
|  `git clone` | Clonar repositórios externos. | Alta |
|  `git add` | Adicionar alterações para um commit. | Alta |
|  `git commit` | Salvar alterações no repositório local. | Alta |
|  `git push` | Empurrar alterações locais para um repositório remoto. | Alta |
|  `git pull` | Puxar alterações remotas para o repositório local. | Alta |
|  `git status` | Ver o estado atual da árvore de trabalho. | Alta |
| `git branch` | Gerenciar [branches](https://git-scm.com/book/pt-br/v2/Branches-no-Git-Branches-em-poucas-palavras) do repositório. | Média
| `git checkout` | Alternar branches locais. | Média |
| `git log` | Visualizar o histórico de alterações do repositório. | Média
| `git merge` | Incorporar duas branches em uma. | Média
| `git rebase` | Também chamado de **squash**, serve para unir múltiplos commits em um só. | Baixa |
| `git stash` | Salva suas alterações temporariamente para serem retomadas mais tarde. | Baixa |

#### Ferramentas

| Ferramenta | Descrição | Prioridade |
| --- | --- | :-: |
| [Semantic Versioning](https://semver.org/lang/pt-BR/) | Especificação para versionamento de software. | Alta |
| [Conventional Commits](https://www.conventionalcommits.org/pt-br/v1.0.0/) | Especificação para mensagens de commit. | Alta |

### GitHub

| Funcionalidade | Prioridade |
| --- | :-: |
| O que são [issues](https://docs.github.com/pt/issues/tracking-your-work-with-issues/about-issues)? | Alta |
| O que são [pull requests](https://docs.github.com/pt/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)? | Alta |
| O que são [milestones](https://docs.github.com/pt/issues/using-labels-and-milestones-to-track-work/about-milestones)? | Média |
| Conexão [via SSH](https://docs.github.com/pt/authentication/connecting-to-github-with-ssh) | Média |
| Assinaturas de commits [via GPG](https://docs.github.com/pt/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) | Baixa |

**Comment by bitterteriyaki** [comment]
Olá, prof. @RochaCarla. Tudo certo?

> O projeto gitflow foi descontinuado.. nao utilizar

Apesar dele estar descontinuado, ele ainda é estável e utilizável. De qualquer maneira, podemos usar o [GitLab Flow](https://about.gitlab.com/blog/2020/03/05/what-is-gitlab-flow/) como alternativa. Espero seu aval.

Atenciosamente,
Caio.

**Comment by jpcfarias** [comment]
O conteudo deve ser Apresentado na reuniao de Segunda. Assim fechando a issue

**Comment by jpcfarias** [comment]
![image](https://github.com/unb-mds/2023-2-Squad06/assets/65802222/62005698-660d-4d05-ac25-860419553339)

**Comment by jpcfarias** [comment]
foi apresentado o tema, esta tudo em ordem
