### ISSUE TITLE
Como configuro meu ambiente?

### ISSUE THREAD

**Issue by bitterteriyaki** [unb-mds/2023-2-Squad06#2]
# Como devo configurar meu ambiente?

Esta issue procura ensinar como configurar seu ambiente para a instalação da aplicação.

## Sistema operacional / WSL

É fortemente recomendando instalar alguma distribuição Linux na sua máquina visto que alguns comandos que você usará daqui para frente só está disponível em sistemas UNIX. Eu pessoalmente recomendo instalar [Ubuntu](https://ubuntu.com/) visto que é uma distribuição fácil para novatos e possui um amplo suporte.

Caso você ainda sim prefira utilizar o Windows, considere usar o WSL para virtualizar um ambiente Linux dentro do Windows. Veja como instalar WSL através [deste guia de instalação](https://learn.microsoft.com/pt-br/windows/wsl/install).

## Editor de texto

Qualquer editor de texto deve servir, mas aqui está uma pequena lista de editores de texto que você pode experimentar:

- [Visual Studio Code](https://code.visualstudio.com/)
- [PyCharm](https://www.jetbrains.com/pycharm/)*
- [Vim](https://www.vim.org/)
- [Sublime Text 3](https://www.sublimetext.com/)

*: somente recomendado caso o trabalho seja feito em Python.

## Docker e Docker Compose

O ambiente da aplicação será disponibilizado através de imagens Docker para facilitar o desenvolvimento do projeto. Você pode instalar todas as dependências do projeto manualmente, porém é muito mais fácil deixar o Docker fazer isso para você. Enquanto Docker facilita a criação e a execução de imagens e containers, Docker Compose facilita o gerenciamento dos mesmos.

- [Guia de instalação do Docker](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)
- [Guia de instalação do Docker Compose](https://docs.docker.com/compose/install/linux/#install-using-the-repository)

Estes guias presumem que você esteja usando uma distribuição Linux baseada em Debian (como Ubuntu, PopOS, etc.).

## Python e Poetry

Como acertado via WhatsApp, o projeto será realizado na linguagem Python. A versão escolhida será UNICAMENTE a 3.11.5, então garanta que não esteja instalando a versão errada na sua máquina.

O [Poetry](https://python-poetry.org/) é um gerenciador de dependências para Python. Não utilizaremos o `pip` visto que ele possui muitos problemas e é muito inferior ao Poetry. Veja como instalar o Poetry vendo [este guia de instalação](https://python-poetry.org/docs/#installation).

**Comment by jpcfarias** [comment]
O conteudo deve ser Apresentado na reuniao de Quarta. Assim fechando a issue

**Comment by jpcfarias** [comment]
![image](https://github.com/unb-mds/2023-2-Squad06/assets/65802222/fb210031-6479-4ddd-bd99-548e013e1269)

**Comment by thegm445** [comment]
<body> <h1> Tema discutido com sucesso na reunião, todos estão (em sua maioria) com o ambiente configurado com sucesso, caso necessite de ajuda, apenas requisitar ao grupo! </h1></body>
