### ISSUE TITLE
Estudo sobre metodologia ágil

### ISSUE THREAD

**Issue by HladczukLe** [unb-mds/2023-2-Squad06#5]
### Details

# Descrição

A metodologia ágil é uma abordagem flexível e colaborativa para o desenvolvimento e gerenciamento de projetos que prioriza a entrega incremental, a adaptação contínua e a satisfação do cliente. Ela se destaca por sua capacidade de lidar com a mudança e promover a melhoria constante ao longo do tempo.

###  Benefícios da metodologia ágil

- Aumento da produtividade
- Melhorias na comunicação
- Mais qualidade
- Integração entre pessoas
- Respostas rápidas para imprevistos e alterações

### Tópicos a serem estudados

- [x] Kanban
- [x] Scrum
- [ ] Lean
- [ ] DSDM
- [ ] FDD
- [ ] ASD
- [ ] SAF

**Comment by bitterteriyaki** [comment]
Já temos um quadro kanban, que o nosso [project board](https://github.com/orgs/unb-mds/projects/3).

**Comment by thegm445** [comment]
Já definimos tudo que precisávamos quanto a isso!
Issue fechada 👍
