### ISSUE TITLE
Decidir o espaço e os horários das reuniões

### ISSUE THREAD

**Issue by thegm445** [unb-mds/2023-2-Squad06#7]
## Decidir o espaço e os horários das reuniões

Aqui temos uma lista de espaços que poderemos ter as próximas reuniões:

- [~Discord~](https://discord.com/)
- [Gather Town](https://www.gather.town/)
- [~Google Meet~](https://meet.google.com/)

Quantos ao horário das reuniões, elas serão feitas nas **segundas** e nas **quartas**, **começando às 20h e terminando às 21h**, então se planeje para não faltá-las.

**Comment by bitterteriyaki** [comment]
A reuniões serão feitas no Gather Town. Você pode acessar a sala de reunião clicando [aqui](https://app.gather.town/invite?token=Wd75EGJQQN-qfmU4voGG).
