### ISSUE TITLE
Desenvolvimento da documentação do projeto

### ISSUE THREAD

**Issue by LuizaMaluf** [unb-mds/2023-2-Squad06#8]
### Descrição

A documentação de projeto de software é fundamental para garantir a compreensão, manutenção e colaboração eficazes em um projeto. Portanto, seguem as seguintes áreas-chave de documentação para serem estudadas:

- **Requisitos do Sistema:** desempenham um papel fundamental no processo de desenvolvimento de software, pois servem como base para o design, implementação e teste do sistema. Devem ser claros, completos, verificáveis e mutuamente consistentes. A compreensão precisa dos requisitos é crucial para evitar erros e problemas durante o desenvolvimento e garantir que o sistema final atenda às expectativas dos usuários.

- **Arquitetura do Software:** é o projeto organizacional de um sistema de software, definindo sua estrutura, componentes e interações para atender aos requisitos do sistema. Desempenha um papel crucial na comunicação e compreensão da visão do sistema.

- **Design Detalhado:** é uma fase crucial no desenvolvimento de software, na qual os conceitos abstratos da arquitetura são traduzidos em especificações técnicas concretas. Visa fornecer instruções precisas para a implementação, garantindo que os desenvolvedores possam criar cada parte do software de forma consistente e eficaz. 

- **Modelagem de Dados:** é o processo de criar uma representação estruturada e organizada dos dados que um sistema de software irá gerenciar. Ela desempenha um papel crucial na definição da estrutura de um sistema e na garantia de que os dados sejam gerenciados de maneira eficaz e precisa.

- **Instruções de Instalação e Configuração:** fornecem orientações passo a passo sobre como instalar e configurar um software ou sistema em um ambiente específico. Essas instruções geralmente incluem requisitos de hardware e software, procedimentos para a instalação do software, configurações recomendadas e ajustes necessários para que o sistema funcione corretamente. 

- **Documentação de Código:** serve como um guia para desenvolvedores, permitindo que entendam rapidamente o código e sua lógica, facilitando a manutenção, depuração e colaboração. Pode incluir descrições de classes, funções, variáveis, bem como explicação de algoritmos, entradas e saídas. 

### Tarefas que garantem um bom entendimento sobre documentação

- [ ] Estudar a documentação de requisitos funcionais e não funcionais.
- [ ] Entender o que seria um diagrama de caso de uso.
- [ ] Identifique tipos de documentação comuns em projetos de software.
- [ ] Pesquise o que é modelagem de dados em um projeto de software.
- [ ] Leia sobre a importância de comentários no código-fonte.
- [ ] Explore diferentes ferramentas de documentação de código disponíveis, como Doxygen, Javadoc ou Sphinx.
- [ ] Pesquise práticas recomendadas para boa documentação de código.

### Sugestão de por onde começar:
[https://guia.dev/pt/pillars/software-architecture/technical-documentation.html](url)
[https://www.youtube.com/watch?v=3Smbhnmue7Y](url)
[https://www.youtube.com/watch?v=N9w5-TChccQ](url)
[https://medium.com/tdx-oficial/4-dicas-de-boas-práticas-de-documentação-de-código-e63df0f0e565](url)
[https://www.devmedia.com.br/introducao-a-requisitos-de-software/29580](url)
[https://www.ibm.com/br-pt/topics/data-modeling](url)

**Comment by bitterteriyaki** [comment]
A documentação do projeto será feita em [Sphinx](https://www.sphinx-doc.org/en/master/).
